### ISSUE TITLE
bug in optimise_2d_grid_model.ipynb

### ISSUE THREAD

**Issue by zhangkaihua88** [alisterburt/torch-cubic-spline-grids#16]
* torch-cubic-b-spline-grid version: 0.0.8
* Python version:3.8.10
* Operating System:linux

### Description

There is a problem with the code displaying the predicted image and the original image in the optimise_2d_grid_model.ipynb file. The predicted image displays the results calculated by formulas rather than predictions

```python
n = 512
x = torch.tensor(np.linspace([0, 0], [1, 1], n))
xx, yy = torch.meshgrid(x[:, 0], x[:, 1], indexing='xy')
y = torch.sin(xx * 2 * torch.pi) + np.sin(yy * 4 * np.pi)
fig, ax = plt.subplots(1, 2)
ax[0].imshow(y, cmap='gray_r', label='prediction')
ax[1].imshow(target_image, cmap='gray_r', label='ground truth')
```

So, The correct display should be like this
```python
n = 512
x = torch.tensor(np.linspace([0, 0], [1, 1], n))
xx, yy = torch.meshgrid(x[:, 0], x[:, 1], indexing='xy')
x = torch.vstack([xx.flatten(), yy.flatten()]).T
y = grid_2d(x).detach().numpy().reshape(512,512)
fig, ax = plt.subplots(1, 2)
ax[0].imshow(y, cmap='gray_r', label='prediction')
ax[1].imshow(target_image, cmap='gray_r', label='ground truth')
```

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by alisterburt** [comment]
Hi @zhangkaihua88 ! Thank you for opening this issue and sorry for the delay replying - I'm taking some time off between jobs right now so checking email less frequently.

You're absolutely right, I pushed a fix in #18 - thanks for the interest!
