### ISSUE TITLE
 range of [0, 1]

### ISSUE THREAD

**Issue by mapleleaf6** [alisterburt/torch-cubic-spline-grids#21]
I noticed that in the implementation of cubic spline interpolation, the grid coordinate system is confined to the range of [0, 1]. I am keen to understand the reasoning behind this design choice.

Could you please shed some light on why the coordinate system was chosen to be within this range? Is this due to specific mathematical or computational considerations, such as enhancing precision or simplifying calculations? Or does this range better suit certain types of applications?

**Comment by alisterburt** [comment]
Hey @mapleleaf6 - great question!

The [0, 1] parametrisation of each dimension is somewhat arbitrary but useful as it means the model is not tied to the scale of the underlying data. E.g an image could be rescaled and the model would be applied the same way.

What would feel most natural for your applications?

**Comment by mapleleaf6** [comment]
Hi @alisterburt, thank you for your response. I now understand the benefits of parameterizing within the [0, 1] range. However, for my application, I need to handle data within an arbitrary range, as my coordinate system has real-world significance. Could you offer any advice on how I might adapt your code to perform B-spline interpolation over any range? I'm looking for ways to implement this while maintaining the integrity and efficiency of the interpolation process.

**Comment by alisterburt** [comment]
For the coordinate system to be well defined you will need to define the domain over which you will approximate the underlying function.

A simple 1d univariate example: 
Trying to approximate `y = sin(x)` over `[x=0, x=2*pi]` you would map the domain of your signal onto the `[u=0, u=1]` range. In this case, you divide your `x` values by `2*pi`. You can easily transform back by multiplying `u` values by `2pi` in this example.

**Comment by mapleleaf6** [comment]
Thank you for the enlightening and detailed explanation of coordinate transformations! I now understand clearly.

I have an additional query regarding the application of torch_cubic_spline_grids for batch data processing. Specifically, I'm interested in understanding if it's feasible to adapt this tool for fitting cubic splines to batch data.  I would appreciate any guidance or tips on implementing cubic spline interpolation in a batch-wise manner using your framework.

**Comment by alisterburt** [comment]
All grids accept arbitrary batches of coordinates, shape `(*, d)` where `d` is the dimensionality of the grid
 
example from the readme, interpolating on a 2d grid:
```python
coords = torch.rand(size=(10, 2))  # values in [0, 1]
interpolants = grid(coords)
```

**Comment by alisterburt** [comment]
I'm going to close this issue, please reopen if you have any issues with the repo
